pipeline {
    agent {
        docker {
            image 'microsoft/dotnet:2.2-sdk'
            args '-p 8080:80'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'dotnet build'
            }
        }
        stage('Test') {
            steps {
                sh 'dotnet test'
            }
        }
        stage('Publish') {
            steps {
                sh 'dotnet publish -c Release -o ./publish'
            }
        }
        stage('Deploy') {
            steps {
                sh 'docker build -t mywebapi ./publish'
                sh 'docker run -p 8080:80 mywebapi'
            }
        }
    }
}
